#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www

info () {
	dig "$2.$1" | awk '/;; ANSWER SECTION/ {getline;
	printf "The subdomain %s is a %s record and points to %s\n", SUB, $4, $5}' SUB="$2"
	}

if [[ $# -gt 1 ]]
then
	info "$1" "$2"
else
	info "$1" "www"
	info "$1" "lb-01"
	info "$1" "web-01"
	info "$1" "web-02"
fi
