#!/usr/bin/env bash
# Creating a custom header for nginx server

sudo apt-get update -y
sudo apt-get install nginx -y
cstm='add_header X-Served-By "$hostname";'
sudo sed -i "43i \\\t$cstm" /etc/nginx/sites-available/default
sudo service nginx restart
