#!/usr/bin/env bash
# configure Nginx server with custom header
# shellcheck disable=SC2016

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
error="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "36i $error" /etc/nginx/sites-available/default
add_header='add_header X-Served-By "$hostname";'
sudo sed -i "41i \\\t$add_header" /etc/nginx/sites-available/default
sudo service nginx restart
