#!/usr/bin/env bash
# Creating a custom header for nginx server

sudo apt update -y
sudo apt install haproxy -y
sudo sed -i '$ aENABLED=1' /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "\nfrontend first_lb\n\tbind *:80\n\tmode http\n\tdefault_backend webservers\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend webservers\n\tbalance roundrobin\n\tserver 2498-web-01 34.139.124.220:80 check\n\tserver 2498-web-02 34.74.25.112:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
