#!/usr/bin/env bash
# Creating a custom header for nginx server

sudo apt-get update -y
sudo apt-get install haproxy -y
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backnodes\n\tbalance roundrobin\n\tserver 2498-web-01 34.139.124.220:80 check\n\tserver 2498-web_02 34.74.25.112:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service nginx restart

