#!/usr/bin/env bash
# displays clock hour

HOURS=0
while [ "$HOURS" -lt 13 ]; do
	echo "Hour: $HOURS"
	MINUTES=1
	while [ "$MINUTES" -lt 60 ]; do
		echo "$MINUTES"
		let MINUTES=MINUTES+1
	done
	let HOURS=HOURS+1
done
